# Generated by Django 3.2 on 2021-06-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Housekeeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=60)),
                ('address_number', models.IntegerField()),
                ('address_district', models.CharField(max_length=30)),
                ('address_complement', models.CharField(max_length=100)),
                ('address_cep', models.CharField(max_length=30)),
                ('address_state', models.CharField(max_length=2)),
                ('ibge_code', models.IntegerField()),
                ('user_photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
