# Generated by Django 3.2 on 2021-06-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel_administrativo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housekeeper',
            name='address_cep',
            field=models.CharField(max_length=8),
        ),
    ]
