# Generated by Django 3.2 on 2021-06-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel_administrativo', '0002_alter_housekeeper_address_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housekeeper',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
