# Generated by Django 3.2 on 2021-06-16 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painel_administrativo', '0003_alter_housekeeper_cpf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housekeeper',
            old_name='address_district',
            new_name='bairro',
        ),
        migrations.RenameField(
            model_name='housekeeper',
            old_name='address_cep',
            new_name='cep',
        ),
        migrations.RenameField(
            model_name='housekeeper',
            old_name='ibge_code',
            new_name='codigo_ibge',
        ),
        migrations.RenameField(
            model_name='housekeeper',
            old_name='address_complement',
            new_name='complemento',
        ),
        migrations.RenameField(
            model_name='housekeeper',
            old_name='address_state',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='housekeeper',
            old_name='user_photo',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='housekeeper',
            old_name='address',
            new_name='logradouro',
        ),
        migrations.RenameField(
            model_name='housekeeper',
            old_name='full_name',
            new_name='nome_completo',
        ),
        migrations.RenameField(
            model_name='housekeeper',
            old_name='address_number',
            new_name='numero',
        ),
        migrations.RenameField(
            model_name='housekeeper',
            old_name='phone_number',
            new_name='telefone',
        ),
    ]
