# Generated by Django 3.2 on 2021-06-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel_administrativo', '0004_auto_20210616_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='housekeeper',
            name='cidade',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='housekeeper',
            name='estado',
            field=models.CharField(max_length=30),
        ),
    ]
